spring.config.activate.on-profile: docker
server.port: 8080
server.error.include-message: always

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080

logging:
  level:
    root: INFO
    se.magnus: DEBUG
